[env:esp32s3]
platform = espressif32 @ 6.13.0
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps =
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.9.0
